#!/usr/bin/python3

from wordhoard import Synonyms
import sys

args = ' '.join(sys.argv[1:])
# args = 'hungry'

if len(args.strip()) == 0:
    print("You'll need to enter a word to continue...")
    exit(1)

syn = Synonyms(search_string=args, output_format='json')
syn_results = syn.find_synonyms()
print(syn_results)
